### ISSUE TITLE
UnicodeEncodeError from MetaData

### ISSUE THREAD

**Issue by qge** [stephenmcd/mezzanine#1132]
When subclassing the Displayable model, there is no Text field specified in the model, and gen_description is True, and the title field is set to a unicode string, then an error is raised in the following lines
        if not description:
            description = str(self)

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/curtis/dev/web/mezzanine/mezzanine/core/models.py", line 240, in save
    super(Displayable, self).save(_args, *_kwargs)
  File "/Users/curtis/dev/web/mezzanine/mezzanine/core/models.py", line 85, in save
    super(Slugged, self).save(_args, *_kwargs)
  File "/Users/curtis/dev/web/mezzanine/mezzanine/core/models.py", line 58, in save
    super(SiteRelated, self).save(_args, *_kwargs)
  File "/Users/curtis/dev/web/mezzanine/mezzanine/core/models.py", line 136, in save
    super(MetaData, self).save(_args, *_kwargs)
  File "/Users/curtis/dev/web/mezzanine/mezzanine/core/models.py", line 195, in save
    super(TimeStamped, self).save(_args, *_kwargs)
  File "/Users/curtis/.environments/dujo2.7.6/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/curtis/.environments/dujo2.7.6/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/curtis/.environments/dujo2.7.6/lib/python2.7/site-packages/django/db/models/base.py", line 635, in _save_table
    forced_update)
  File "/Users/curtis/.environments/dujo2.7.6/lib/python2.7/site-packages/django/db/models/base.py", line 679, in _do_update
    return filtered._update(values) > 0
  File "/Users/curtis/.environments/dujo2.7.6/lib/python2.7/site-packages/django/db/models/query.py", line 510, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/Users/curtis/.environments/dujo2.7.6/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 980, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/Users/curtis/.environments/dujo2.7.6/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/Users/curtis/.environments/dujo2.7.6/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/curtis/.environments/dujo2.7.6/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/Users/curtis/.environments/dujo2.7.6/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/Users/curtis/.environments/dujo2.7.6/lib/python2.7/site-packages/MySQLdb/cursors.py", line 187, in execute
    query = query % tuple([db.literal(item) for item in args])
  File "/Users/curtis/.environments/dujo2.7.6/lib/python2.7/site-packages/MySQLdb/connections.py", line 278, in literal
    return self.escape(o, self.encoders)
  File "/Users/curtis/.environments/dujo2.7.6/lib/python2.7/site-packages/MySQLdb/connections.py", line 203, in string_literal
    return db.string_literal(obj)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

**Comment by dharmagetic** [comment]
Hi, i was faced with this problem. Is there a solution other than change /mezzanine/core/models.py ?

**Comment by sourenaraya** [comment]
Same issue.
