### ISSUE TITLE
Cannot resolve bases for [<ModelState: 'shop.Category'>](using development version)

### ISSUE THREAD

**Issue by kulbir** [stephenmcd/mezzanine#1198]
Hi guys,
I just install the `latest development` version of `Mezzanine`. 
When I try to run `syncdb`. I get an error. 
```
Running migrations:
  Applying contenttypes.0001_initial...Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/sandhu/Envs/carjojo/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/sandhu/Envs/carjojo/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/sandhu/Envs/carjojo/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/sandhu/Envs/carjojo/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/sandhu/Envs/carjojo/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/Users/sandhu/Envs/carjojo/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 27, in handle_noargs
    call_command("migrate", **options)
  File "/Users/sandhu/Envs/carjojo/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/Users/sandhu/Envs/carjojo/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/sandhu/Envs/carjojo/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/Users/sandhu/Envs/carjojo/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/Users/sandhu/Envs/carjojo/lib/python2.7/site-packages/django/db/migrations/executor.py", line 96, in apply_migration
    if self.detect_soft_applied(migration):
  File "/Users/sandhu/Envs/carjojo/lib/python2.7/site-packages/django/db/migrations/executor.py", line 140, in detect_soft_applied
    apps = project_state.render()
  File "/Users/sandhu/Envs/carjojo/lib/python2.7/site-packages/django/db/migrations/state.py", line 75, in render
    "for more" % new_unrendered_models
django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'shop.Category'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/1.7/topics/migrations/#dependencies for more

```
Here are the full traceback https://gist.github.com/kulbir/82b16f64e2e0f6084179.

Thanks,
Kulbir

**Comment by stephenmcd** [comment]
You've already posted this to the mailing list which is preferable, no need to double post.
