### ISSUE TITLE
mezzanine_events migrations not working after multilanguage activated.

### ISSUE THREAD

**Issue by itztli** [stephenmcd/mezzanine#1278]
Hi all!
I have a project that upgrade with the last version of mezzanine to include multilanguage support. I modified /registration/models.py in order to run this version of mezzanine. I also create mezzanine_events/translation.py:

from modeltranslation.translator import translator, TranslationOptions
from .models import Event, EventContainer

class TranslatedEvent(TranslationOptions):
    fields = ('rsvp',)

class TranslatedEventContainer(TranslationOptions):
    fields = ()

translator.register(Event, TranslatedEvent)
translator.register(EventContainer, TranslatedEventContainer)

The properties was traslated but I got a error when run:

python manage.py migrate

The error:

Running migrations:
  Applying blog.0002_auto_20150422_1237...Traceback (most recent call last):
  File "./manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vdelaluz/virtualenvs/sciesmex/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/vdelaluz/virtualenvs/sciesmex/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vdelaluz/virtualenvs/sciesmex/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/vdelaluz/virtualenvs/sciesmex/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/vdelaluz/virtualenvs/sciesmex/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 160, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/home/vdelaluz/virtualenvs/sciesmex/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 63, in migrate
    self.apply_migration(migration, fake=fake)
  File "/home/vdelaluz/virtualenvs/sciesmex/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 91, in apply_migration
    if self.detect_soft_applied(migration):
  File "/home/vdelaluz/virtualenvs/sciesmex/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 135, in detect_soft_applied
    apps = project_state.render()
  File "/home/vdelaluz/virtualenvs/sciesmex/local/lib/python2.7/site-packages/django/db/migrations/state.py", line 71, in render
    raise InvalidBasesError("Cannot resolve bases for %r\nThis can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)\n in an app with no migrations; see https://docs.djangoproject.com/en/1.7/topics/migrations/#dependencies for more" % new_unrendered_models)
django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'mezzanine_events.Event'>, <ModelState: 'mezzanine_events.EventContainer'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/1.7/topics/migrations/#dependencies for more

django-admin --version
1.7.1

**Comment by stephenmcd** [comment]
No idea. Really doesn't look like something in Mezzanine's code - I'd suggest opening an issue on modeltranslation and/or events. You could also post this to the mailing list where someone might be able to give some advice.

**Comment by itztli** [comment]
Thank you!
I think that modeltranslation in mezzanine needs a lot of work to become stable.

**Comment by Kniyl** [comment]
Some random thoughts at first glance:
 * are you models subclasses of ```Page``` or ```RichTextPage```? and did you try using ```mezzanine.pages.translation.TranslatedPage``` or ```mezzanine.pages.translation.TranslatedRichTextPage``` instead of ```modeltranslation.translation.TranslationOptions```?
 * did try to create a migration file for your translation fields and your app containing the Event model? See http://mezzanine.jupo.org/docs/model-customization.html#field-injection-caveats for a rough idea on the way to do it. Extra help might be found at https://github.com/deschler/django-modeltranslation/issues/106 or http://south.readthedocs.org/en/latest/customfields.html#example

I’ll try to dig into it soon and provide a better answer than that.
