### ISSUE TITLE
Pillow can't install on Mezzanine with Python 3.5 

### ISSUE THREAD

**Issue by zruu** [stephenmcd/mezzanine#1471]
Got some trouble running the installation of Mezzanine with Python 3.5 on my virtual environment (12.0.2). Here's some tracebacks from the installation process:

###### Pillow:

`Running setup.py install for pillow
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/folders/3g/br3ztr3d69g12z5vw4tfqj3w0000gq/T/pip-build-613inq8u/pillow/setup.py", line 767, in <module>
        zip_safe=not debug_build(),
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/zruu/Django/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 338, in run
        self.build_extensions()
      File "/var/folders/3g/br3ztr3d69g12z5vw4tfqj3w0000gq/T/pip-build-613inq8u/pillow/setup.py", line 515, in build_extensions
        % (f, f))
    ValueError: --enable-jpeg requested but jpeg not found, aborting.
Complete output from command /Users/zruu/Django/bin/python3.5 -c "import setuptools, tokenize;__file__='/var/folders/3g/br3ztr3d69g12z5vw4tfqj3w0000gq/T/pip-build-613inq8u/pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/3g/br3ztr3d69g12z5vw4tfqj3w0000gq/T/pip-swcv4f73-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/zruu/Django/bin/../include/site/python3.5:`

###### More Pillow traceback:

`running build_ext
    
    Traceback (most recent call last):
    
      File "<string>", line 1, in <module>
    
      File "/var/folders/3g/br3ztr3d69g12z5vw4tfqj3w0000gq/T/pip-build-613inq8u/pillow/setup.py", line 767, in <module>
    
        zip_safe=not debug_build(),
    
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
    
        dist.run_commands()
    
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
    
        self.run_command(cmd)
    
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
    
        cmd_obj.run()
    
      File "/Users/zruu/Django/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
    
        return orig.install.run(self)
    
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/install.py", line 539, in run
    
        self.run_command('build')
    
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
    
        self.distribution.run_command(command)
    
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
    
        cmd_obj.run()
    
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build.py", line 135, in run
    
        self.run_command(cmd_name)
    
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
    
        self.distribution.run_command(command)
    
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
    
        cmd_obj.run()
    
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 338, in run
    
        self.build_extensions()
    
      File "/var/folders/3g/br3ztr3d69g12z5vw4tfqj3w0000gq/T/pip-build-613inq8u/pillow/setup.py", line 515, in build_extensions
    
        % (f, f))
    
    ValueError: --enable-jpeg requested but jpeg not found, aborting.
    
    ----------------------------------------
    Command "/Users/zruu/Django/bin/python3.5 -c "import setuptools, tokenize;__file__='/var/folders/3g/br3ztr3d69g12z5vw4tfqj3w0000gq/T/pip-build-613inq8u/pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/3g/br3ztr3d69g12z5vw4tfqj3w0000gq/T/pip-swcv4f73-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/zruu/Django/bin/../include/site/python3.5" failed with error code 1 in /var/folders/3g/br3ztr3d69g12z5vw4tfqj3w0000gq/T/pip-build-613inq8u/pillow`

**Comment by ryneeverett** [comment]
I don't think this is a 3.5-specific issue, but I wonder if you have `libjpeg-dev` and `python-imaging` installed.
