### ISSUE TITLE
UnicodeDecodeError in utils\device.py

### ISSUE THREAD

**Issue by vitalybe** [stephenmcd/mezzanine#1485]
Python 2.7. Mezzazine version 4.01.

I assume it is related to #1116. Call stack:

    Internal Server Error: /faq/
    Traceback (most recent call last):
      File "/home/ubuntu/.virtualenvs/dojo_portal/local/lib/python2.7/site-    packages/django/core/handlers/base.py", line 108, in get_response
        response = middleware_method(request)
      File "/home/ubuntu/.virtualenvs/dojo_portal/local/lib/python2.7/site-packages/mezzanine/core/middleware.py", line 212, in process_request
        cache_key = cache_key_prefix(request) + request.get_full_path()
      File "/home/ubuntu/.virtualenvs/dojo_portal/local/lib/python2.7/site-packages/mezzanine/utils/cache.py", line 78, in cache_key_prefix
    device_from_request(request) or "default",
      File "/home/ubuntu/.virtualenvs/dojo_portal/local/lib/python2.7/site-packages/mezzanine/utils/device.py", line 30, in device_from_request
        if ua_string.lower() in user_agent:
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 2: ordinal not in range(128)

The error is on this line: 
https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/utils/device.py#L30

**Comment by stephenmcd** [comment]
Can you provide some code that will reproduce this?

**Comment by stephenmcd** [comment]
Please re-open if you can provide a reproducible test case.
