### ISSUE TITLE
django fails replacing FK "sites.Site" string with actual class

### ISSUE THREAD

**Issue by gradel** [stephenmcd/mezzanine#1514]
After facing this exception in my project could reproduce it on a plain testing install:

```
Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/gerald/tests/mezzanine/env/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/db/models/base.py", line 401, in __init__
    rel_obj = kwargs.pop(field.name)
KeyError: 'site'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gerald/tests/mezzanine/env/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/db/models/base.py", line 406, in __init__
    val = kwargs.pop(field.attname)
KeyError: 'site_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gerald/tests/mezzanine/env/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/gerald/tests/mezzanine/env/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gerald/tests/mezzanine/env/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/contrib/sitemaps/views.py", line 16, in inner
    response = func(request, *args, **kwargs)
  File "/home/gerald/tests/mezzanine/env/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/contrib/sitemaps/views.py", line 67, in sitemap
    protocol=req_protocol))
  File "/home/gerald/tests/mezzanine/mezzanine/mezzanine/core/sitemaps.py", line 38, in get_urls
    return super(DisplayableSitemap, self).get_urls(**kwargs)
  File "/home/gerald/tests/mezzanine/env/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    urls = self._urls(page, protocol, domain)
  File "/home/gerald/tests/mezzanine/env/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/contrib/sitemaps/__init__.py", line 112, in _urls
    for item in self.paginator.page(page).object_list:
  File "/home/gerald/tests/mezzanine/env/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/contrib/sitemaps/__init__.py", line 71, in _get_paginator
    return paginator.Paginator(self.items(), self.limit)
  File "/home/gerald/tests/mezzanine/mezzanine/mezzanine/core/sitemaps.py", line 27, in items
    return list(Displayable.objects.url_map(in_sitemap=True).values())
  File "/home/gerald/tests/mezzanine/mezzanine/mezzanine/core/managers.py", line 366, in url_map
    home = self.model(title=_("Home"))
  File "/home/gerald/tests/mezzanine/env/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/db/models/base.py", line 408, in __init__
    val = field.get_default()
  File "/home/gerald/tests/mezzanine/env/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/db/models/fields/related.py", line 902, in get_default
    if isinstance(field_default, self.remote_field.model):
TypeError: isinstance() arg 2 must be a type or tuple of types
[20/Jan/2016 15:36:37] "GET /sitemap.xml HTTP/1.1" 500 123470
```

self.remote_field.model at this point is the string "sites.Site".
This change in core/models.py worked for me:

    from django.contrib.sites.models import Site
    site = models.ForeignKey(Site, editable=False)

Test suite showed no errors.

**Comment by stephenmcd** [comment]
94d57294bcc1e934fdd723546be7ea15bb9dcd1a
