### ISSUE TITLE
KeyError when replacing 'TEMPLATE_CONTEXT_PROCESSORS' with 'context_processors' dict

### ISSUE THREAD

**Issue by henri-hulski** [stephenmcd/mezzanine#1515]
When upgrading to Django 1.9 and Mezzanine 4.1 I replace TEMPLATE_CONTEXT_PROCESSORS settings with the 'context_processors' dict and also django.core.context_processors with django.template.context_processors. So I got:
``` python
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(PROJECT_ROOT, "templates")
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                # Insert your TEMPLATE_CONTEXT_PROCESSORS here
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.debug",
                "django.template.context_processors.i18n",
                "django.template.context_processors.static",
                "django.template.context_processors.media",
                "django.template.context_processors.request",
                "django.template.context_processors.tz",
                "mezzanine.conf.context_processors.settings",
                "mezzanine.pages.context_processors.page",
            ],
            "builtins": [
                "mezzanine.template.loader_tags",
            ],
        },
    },
```
I get a `KeyError` for `TEMPLATE_CONTEXT_PROCESSORS` in `utils/conf.py`.
Here the backtrace:
```
mod_wsgi (pid=27942): Target WSGI script '/home/hempis/web/hempis.openhomeo.info/private/hempis/hempis/hempis/wsgi.py' cannot be loaded as Python module.
mod_wsgi (pid=27942): Exception occurred processing WSGI script '/home/hempis/web/hempis.openhomeo.info/private/hempis/hempis/hempis/wsgi.py'.
Traceback (most recent call last):
  File "/home/hempis/web/hempis.openhomeo.info/private/hempis/hempis/hempis/wsgi.py", line 23, in <module>
    application = get_wsgi_application()
  File "/home/hempis/web/hempis.openhomeo.info/private/hempis/venv/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "/home/hempis/web/hempis.openhomeo.info/private/hempis/venv/lib/python2.7/site-packages/django/__init__.py", line 17, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/hempis/web/hempis.openhomeo.info/private/hempis/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    return '<LazySettings [Unevaluated]>'
  File "/home/hempis/web/hempis.openhomeo.info/private/hempis/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    
  File "/home/hempis/web/hempis.openhomeo.info/private/hempis/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    for setting in dir(global_settings):
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/hempis/web/hempis.openhomeo.info/private/hempis/hempis/hempis/settings.py", line 461, in <module>
    set_dynamic_settings(globals())
  File "/home/hempis/web/hempis.openhomeo.info/private/hempis/venv/lib/python2.7/site-packages/mezzanine/utils/conf.py", line 89, in set_dynamic_settings
    __import__("modeltranslation")
KeyError: u'TEMPLATE_CONTEXT_PROCESSORS'
```

**Comment by henri-hulski** [comment]
Ok, after restarting Apache the error seems to be gone.
So sorry for the noise. Closing
