### ISSUE TITLE
getting an error while installation for process of mezzanine

### ISSUE THREAD

**Issue by shauntrick** [stephenmcd/mezzanine#1535]
python manage.py createdb
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/usr/lib/python2.7/dist-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/mezzanine/generic/models.py", line 20, in <module>
    class ThreadedComment(Comment):
  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 168, in __new__
    new_class.add_to_class(obj_name, obj)
  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 297, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib/python2.7/dist-packages/mezzanine/generic/fields.py", line 77, in contribute_to_class
    extant_fields = cls._meta._forward_fields_map
AttributeError: 'Options' object has no attribute '_forward_fields_map'

**Comment by stephenmcd** [comment]
Works fine for me - you might like to try the mailing list for help.
