### ISSUE TITLE
custom model inheriting from RichTextPage causes FieldError

### ISSUE THREAD

**Issue by hjwp** [stephenmcd/mezzanine#1595]
Minimal repro:

- take example from the docs at http://mezzanine.jupo.org/docs/content-architecture.html#creating-custom-content-types but instead of extending Page, extend RichTextPage.  Just one model does it:

```python
from django.db import models
from mezzanine.pages.models import RichTextPage

class Author(RichTextPage):
    dob = models.DateField("Date of birth")
```

After a `makemigrations`, trying to load the site home, or the admin/pages will give:

```
django.core.exceptions.FieldError: Invalid field name(s) given in select_related: 'author'. Choices are: site, parent, richtextpage, link, form, gallery
```

**Comment by hjwp** [comment]
(this does not happen if you simply extend the `Page` class)

**Comment by hjwp** [comment]
Full traceback:

```
Internal Server Error: /
Traceback (most recent call last):
  File "/path/to/python3.5/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/path/to/python3.5/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/path/to/python3.5/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/path/to/python3.5/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/path/to/python3.5/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/path/to/python3.5/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/path/to/python3.5/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/path/to/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/path/to/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/path/to/python3.5/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/path/to/python3.5/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/path/to/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/path/to/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/path/to/python3.5/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/path/to/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/path/to/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/path/to/python3.5/site-packages/mezzanine/template/__init__.py", line 61, in render
    return tag_func(context, token)
  File "/path/to/python3.5/site-packages/mezzanine/pages/templatetags/pages_tags.py", line 62, in page_menu
    content_model="link").get(slug=slug)
  File "/path/to/python3.5/site-packages/django/db/models/query.py", line 381, in get
    num = len(clone)
  File "/path/to/python3.5/site-packages/django/db/models/query.py", line 240, in __len__
    self._fetch_all()
  File "/path/to/python3.5/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/path/to/python3.5/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/path/to/python3.5/site-packages/django/db/models/sql/compiler.py", line 837, in execute_sql
    sql, params = self.as_sql()
  File "/path/to/python3.5/site-packages/django/db/models/sql/compiler.py", line 382, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "/path/to/python3.5/site-packages/django/db/models/sql/compiler.py", line 48, in pre_sql_setup
    self.setup_query()
  File "/path/to/python3.5/site-packages/django/db/models/sql/compiler.py", line 39, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select()
  File "/path/to/python3.5/site-packages/django/db/models/sql/compiler.py", line 215, in get_select
    related_klass_infos = self.get_related_selections(select)
  File "/path/to/python3.5/site-packages/django/db/models/sql/compiler.py", line 762, in get_related_selections
    ', '.join(_get_field_choices()) or '(none)',
django.core.exceptions.FieldError: Invalid field name(s) given in select_related: 'author'. Choices are: site, parent, richtextpage, link, form, gallery
```

**Comment by jerivas** [comment]
This is by design. There's a note in the section of the docs you've linked:
> When creating custom content types, you must inherit directly from the Page model. Further levels of subclassing are currently not supported. Therefore you cannot subclass the RichTextPage or any other custom content types you create yourself. Should you need to implement a WYSIWYG editable field in the way the RichTextPage model does, you can simply subclass both Page and RichText, the latter being imported from mezzanine.core.models.

**Comment by hjwp** [comment]
Sorry, should have read the friendly manual!
