### ISSUE TITLE
fab deploy command error

### ISSUE THREAD

**Issue by mketiku** [stephenmcd/mezzanine#1642]
running the default fab file gives me this error message, what gives @stephenmcd ?
I am using ubuntu 16, with a virtualenv for python 2. 

``` shell
(intranet-virt.back) mketiku@Y11S:~/Projects/in_app$ fab deploy
[10.100.30.239] Executing task 'deploy'

------
deploy
------

Project does not exist in host server: insider_intranet
Would you like to create it? [Y/n] y

------
create
------


$ locale -a ->

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/usr/lib/python2.7/dist-packages/fabric/tasks.py", line 387, in execute
    multiprocessing
  File "/usr/lib/python2.7/dist-packages/fabric/tasks.py", line 277, in _execute
    return task.run(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/mketiku/Projects/in_app/fabfile.py", line 212, in logged
    return func(*args, **kawrgs)
  File "/home/mketiku/Projects/in_app/fabfile.py", line 607, in deploy
    create()
  File "/usr/lib/python2.7/dist-packages/fabric/tasks.py", line 171, in __call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/mketiku/Projects/in_app/fabfile.py", line 212, in logged
    return func(*args, **kawrgs)
  File "/home/mketiku/Projects/in_app/fabfile.py", line 467, in create
    if locale not in run("locale -a"):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 1175: ordinal not in range(128)
Disconnecting from 10.100.30.239... done.
```

**Comment by gfranxman** [comment]
What's the output of running locale -a on your remote machine?

**Comment by mketiku** [comment]
Here is the locale -a ouput
[local_output.txt](https://github.com/stephenmcd/mezzanine/files/407713/local_output.txt)

**Comment by gfranxman** [comment]
Looks like something odd on line 105.

I believe you can clean it up with something along the lines of:
 $ sudo locale-gen --purge bokm�l

**Comment by gfranxman** [comment]
Whoa -- dont run that locale-gen command !    It doesnt purge the locale on
the command line, it purges everything else!!!

**Comment by mketiku** [comment]
phew!, I did not run the local-gen command, any other ideas?
