### ISSUE TITLE
TypeError at /admin/media-library/browse/

### ISSUE THREAD

**Issue by karalics** [stephenmcd/mezzanine#1650]
By clicking on Media (Backend) after a fresh Virtualenv, Mezzanine Install and `createdb` with content

`render_to_response() got an unexpected keyword argument 'context_instance'`

```
Request Method: 	GET
Request URL: 	http://localhost:8000/admin/media-library/browse/
Django Version: 	1.10
Exception Type: 	TypeError
Exception Value: 	
```

`render_to_response() got an unexpected keyword argument 'context_instance'`

```
Exception Location: 	/home/slavi/virtualenvs/mezzanine42/lib/python3.4/site-packages/filebrowser_safe/views.py in browse, line 188
Python Executable: 	/home/slavi/virtualenvs/mezzanine42/bin/python
Python Version: 	3.4.2
Python Path: 	
```

```
['/home/slavi/virtualenvs/mezzanine42/default',
 '/opt/python342/lib/python34.zip',
 '/opt/python342/lib/python3.4',
 '/opt/python342/lib/python3.4/plat-linux',
 '/opt/python342/lib/python3.4/lib-dynload',
 '/home/slavi/virtualenvs/mezzanine42/lib/python3.4/site-packages']
```

Python 3.4.2
Django==1.10
Mezzanine==4.2.0
Pillow==3.3.0
beautifulsoup4==4.5.1
bleach==1.4.3
chardet==2.3.0
django-contrib-comments==1.7.2
filebrowser-safe==0.4.3
future==0.15.2
grappelli-safe==0.4.2
html5lib==0.9999999
oauthlib==1.1.2
pytz==2016.6.1
requests==2.11.0
requests-oauthlib==0.6.2
six==1.10.0
tzlocal==1.2.2

# Command line Traceback: 

```
[15/Aug/2016 06:55:50] "GET /favicon.ico/ HTTP/1.1" 404 1696
[15/Aug/2016 06:55:52] "GET /admin/media-library/ HTTP/1.1" 302 0
Internal Server Error: /admin/media-library/browse/
Traceback (most recent call last):
  File "/home/slavi/virtualenvs/mezzanine42/lib/python3.4/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/slavi/virtualenvs/mezzanine42/lib/python3.4/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/slavi/virtualenvs/mezzanine42/lib/python3.4/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/slavi/virtualenvs/mezzanine42/lib/python3.4/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/slavi/virtualenvs/mezzanine42/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/slavi/virtualenvs/mezzanine42/lib/python3.4/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/slavi/virtualenvs/mezzanine42/lib/python3.4/site-packages/filebrowser_safe/views.py", line 188, in browse
    }, context_instance=Context(request))
TypeError: render_to_response() got an unexpected keyword argument 'context_instance'
[15/Aug/2016 06:55:52] "GET /admin/media-library/browse/ HTTP/1.1" 500 86040
Not Found: /favicon.ico/
[15/Aug/2016 06:55:52] "GET /favicon.ico/ HTTP/1.1" 404 1696
```

**Comment by karalics** [comment]
It seems, that in django 1.10 context_instance was removed from render_to_response from django.shortcuts.

see https://github.com/django/django/commit/9023696613b278bb96a2ab5744da5c2bac023ad7

**Comment by ryneeverett** [comment]
See [the latest filbrowser-safe commit](https://github.com/stephenmcd/filebrowser-safe/commit/5e30a021f89f27100f137f6aab692303b4a6b2bd).

**Comment by karalics** [comment]
Sorry Didn't see it.. Thx for the hint..

**Comment by stephenmcd** [comment]
I'd forgotten to push new releases for FB/Grappelli when I pushed Mezzanine 4.2, which was part of the problem. I've pushed new versions of those now, so installing from PyPI should work.
