### ISSUE TITLE
KeyError: 'no_color' in base.py, l. 314

### ISSUE THREAD

**Issue by Ge0** [stephenmcd/mezzanine#1691]
Raised when I try to `python manage.py createdb` with those settings:

```
USE_MODELTRANSLATION = True

LANGUAGE_CODE = 'en'

LANGUAGES = (
    ('en', _('English')),
    ('fr', _('French'))
)
```

```
Django-modeltranslation is installed for this project and you have specified to use i18n.
Would you like to update translation fields from the default ones? (yes/no): yes
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ge0/envs/bakadeshi/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/ge0/envs/bakadeshi/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ge0/envs/bakadeshi/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ge0/envs/bakadeshi/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/ge0/envs/bakadeshi/lib/python3.5/site-packages/mezzanine/core/management/commands/createdb.py", line 61, in handle
    func()
  File "/home/ge0/envs/bakadeshi/lib/python3.5/site-packages/mezzanine/core/management/commands/createdb.py", line 151, in translation_fields
    verbosity=self.verbosity, interactive=False)
  File "/home/ge0/envs/bakadeshi/lib/python3.5/site-packages/django/core/management/base.py", line 314, in execute
    if options['no_color']:
KeyError: 'no_color'
```

**Comment by Ge0** [comment]
My bad, it looks like it is a django issue.

What should I do with this issue then?

**Comment by Ge0** [comment]
Apparently django is fine:

https://code.djangoproject.com/ticket/26315#comment:7

I'll keep digging on mezzanine's side.

**Comment by stephenmcd** [comment]
c244b603a6efab5062dcf97b1e12227e61ba4fb8
