### ISSUE TITLE
import_blogger error > AttributeError: 'function' object has no attribute 'func_name'

### ISSUE THREAD

**Issue by emTr0** [stephenmcd/mezzanine#1759]
Posted on the [Google Group](https://groups.google.com/d/msg/mezzanine-users/hbISLWKMJ1k/GErWvmkzAgAJ). Posting here for maximum exposure.

Using this info > http://mezzanine.jupo.org/docs/blog-importing.html#importing-from-blogger

I installed "gdata" via pip.

The import_blogger command throws the following error:

```
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/emtr0/.virtualenvs/emtr0dotcom/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/emtr0/.virtualenvs/emtr0dotcom/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/emtr0/.virtualenvs/emtr0dotcom/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/emtr0/.virtualenvs/emtr0dotcom/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/emtr0/.virtualenvs/emtr0dotcom/lib/python3.5/site-packages/mezzanine/blog/management/base.py", line 170, in handle
    self.handle_import(options)
  File "/home/emtr0/.virtualenvs/emtr0dotcom/lib/python3.5/site-packages/mezzanine/blog/management/commands/import_blogger.py", line 35, in handle_import
    from gdata import service
  File "/home/emtr0/.virtualenvs/emtr0dotcom/lib/python3.5/site-packages/gdata/__init__.py", line 27, in <module>
    import atom
  File "/home/emtr0/.virtualenvs/emtr0dotcom/lib/python3.5/site-packages/atom/__init__.py", line 133, in <module>
    CreateClassFromXMLString)
  File "/home/emtr0/.virtualenvs/emtr0dotcom/lib/python3.5/site-packages/atom/__init__.py", line 97, in mark_deprecated
    optional_warn_function.func_name = f.func_name
AttributeError: 'function' object has no attribute 'func_name'
```
Thanks for the help!

**Comment by emTr0** [comment]
I've since resorted to using the RSS importer but Blogger importer still doesn't work.

**Comment by stephenmcd** [comment]
> Posting here for maximum exposure.

Please don't do that, now there are two sets of conversations to support. As we note in the README, if you've found a bug, file an issue. If you're unsure, post to the mailing list.

As for the traceback you've posted, it shows the error is with a third-party lib, so you'll need to chase it up there.

**Comment by emTr0** [comment]
Thanks.
