### ISSUE TITLE
import_blogger erroring with UnicodeDecodeError

### ISSUE THREAD

**Issue by HenryMehta** [stephenmcd/mezzanine#1804]
I'm running the following to load a blogger site:
`python manage.py import_blogger --mezzanine-user=admin --blogger-id=XXX`
where XXX has been replaced with the blogger id and I'm getting the following Traceback:
```
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/henry/Documents/Sites/Development/ExiledRobin/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/henry/Documents/Sites/Development/ExiledRobin/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/henry/Documents/Sites/Development/ExiledRobin/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/henry/Documents/Sites/Development/ExiledRobin/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/henry/Documents/Sites/Development/ExiledRobin/env/local/lib/python2.7/site-packages/mezzanine/blog/management/base.py", line 170, in handle
    self.handle_import(options)
  File "/home/henry/Documents/Sites/Development/ExiledRobin/env/local/lib/python2.7/site-packages/mezzanine/blog/management/commands/import_blogger.py", line 84, in handle_import
    pub_date=published_date, tags=tags)
  File "/home/henry/Documents/Sites/Development/ExiledRobin/env/local/lib/python2.7/site-packages/mezzanine/blog/management/base.py", line 68, in add_post
    title = decode_entities(title)
  File "/home/henry/Documents/Sites/Development/ExiledRobin/env/local/lib/python2.7/site-packages/mezzanine/utils/html.py", line 77, in decode_entities
    return re.sub("&#?\w+;", decode, html.replace("&amp;", "&"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 37: ordinal not in range(128)
```

**Comment by kenbolton** [comment]
Hi Henry,
Please use the mailing list, where this question gets answered quite often.
