### ISSUE TITLE
NoReverseMatch rest_framework once mezzanine.accounts is uncommented in settings

### ISSUE THREAD

**Issue by mike1573** [stephenmcd/mezzanine#1827]
Hi,
   I'm getting "NoReverseMatch: u'rest_framework' is not a registered namespace" once mezzanine.accounts is uncommented in settings. Note I have seen a similar issue being raised in the mailing-list with a response that the issue cannot be replicated with a vanilla install of mezzanine. For my scenario everything works up until mezzanine_api is installed, specifically when the # REST API SETTINGS #... are added to the main settings.py file. So mezzanine.accounts will fine without mezzanine_api and vice-versa... but all fail once enable in full together.

Versions installed:

Mezzanine 4.2.3
Django 1.10.8
Python 2.7.6
SQLite 3.8.2
mezzanine-api (0.6.1)
mezzanine-client (0.2.2)

Trace:

Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7f3fc934c668>
Traceback (most recent call last):
  File "/home/mike1573/cart2-env/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/mike1573/cart2-env/local/lib/python2.7/site-packages/mezzanine/core/management/commands/runserver.py", line 163, in inner_run
    super(Command, self).inner_run(*args, **kwargs)
  File "/home/mike1573/cart2-env/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/home/mike1573/cart2-env/local/lib/python2.7/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/mike1573/cart2-env/local/lib/python2.7/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/mike1573/cart2-env/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/mike1573/cart2-env/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/mike1573/cart2-env/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/mike1573/cart2-env/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/mike1573/cart2-env/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/mike1573/cart2-env/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/mike1573/cart2-env/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/mike1573/cart-root2/cart/cart/urls.py", line 93, in <module>
    url("^", include("mezzanine.urls")),
  File "/home/mike1573/cart2-env/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/mike1573/cart2-env/local/lib/python2.7/site-packages/mezzanine/urls.py", line 64, in <module>
    url("^", include("mezzanine.accounts.urls")),
  File "/home/mike1573/cart2-env/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/mike1573/cart2-env/local/lib/python2.7/site-packages/mezzanine/accounts/urls.py", line 29, in <module>
    url("^%s%s$" % (LOGIN_URL.strip("/"), _slash),
  File "/home/mike1573/cart2-env/local/lib/python2.7/site-packages/django/utils/functional.py", line 111, in __wrapper__
    res = func(*self.__args, **self.__kw)
  File "/home/mike1573/cart2-env/local/lib/python2.7/site-packages/django/urls/base.py", line 87, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: u'rest_framework' is not a registered namespace

**Comment by stephenmcd** [comment]
Please raise this with that project.
