### ISSUE TITLE
vscode debug issue

### ISSUE THREAD

**Issue by phimor** [stephenmcd/mezzanine#1845]
`Traceback (most recent call last):
  File "D:\software\program_books\python\exercises\myproject_mezzanine/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "D:\software\program\python36_64\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "D:\software\program\python36_64\lib\site-packages\django\core\management\__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\software\program\python36_64\lib\site-packages\django\core\management\base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\software\program\python36_64\lib\site-packages\django\core\management\commands\runserver.py", line 58, in execute
    super(Command, self).execute(*args, **options)
  File "D:\software\program\python36_64\lib\site-packages\django\core\management\base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "D:\software\program\python36_64\lib\site-packages\django\core\management\commands\runserver.py", line 97, in handle
    self.run(**options)
  File "D:\software\program\python36_64\lib\site-packages\django\core\management\commands\runserver.py", line 108, in run
    self.inner_run(None, **options)
TypeError: inner_run() got multiple values for argument 'show_banner'`

**Comment by KBPsystem777** [comment]
Hi @phimor  - can you please provide steps to re-produce this? I think I have the same issue. Thanks

**Comment by thatbudakguy** [comment]
Same issue here.

**Comment by kenbolton** [comment]
Would you please specify which version of Mezzanine you are using?

**Comment by thatbudakguy** [comment]
Mezzanine 4.2.3 / Django 1.10.8

the `--nobanner` flag didn't fix the issue for me. I'm using the vscode suggested `launch.json` values for django, with the `--nobanner` flag added:
```js
{
            "name": "Python: Django",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${workspaceFolder}/manage.py",
            "cwd": "${workspaceFolder}",
            "args": [
                "runserver",
                "--noreload",
                "--nothreading",
                "--nobanner"
            ],
            "env": {},
            "envFile": "${workspaceFolder}/.env",
            "debugOptions": [
                "RedirectOutput",
                "DjangoDebugging"
            ]
        }
```

**Comment by kenbolton** [comment]
Does runserver work from a normal terminal, or using the terminal in VS Code?

**Comment by thatbudakguy** [comment]
it works normally using the terminal in vscode, yep.

**Comment by stephenmcd** [comment]
I'm confident there's nothing specific to Mezzanine that would be causing the exception you posted.

**Comment by zmbq** [comment]
I am having the exact same issue. I have multiple Django projects and can debug all of them properly in Visual Studio Code. This issue only exists with Mezzanine (version 4.2.3 or 4.3.1) - you simply can't debug a Django app if Mezzanine is installed. I am going to stop using Mezzanine, as I like Visual Studio Code better than I like Mezzanine.
