### ISSUE TITLE
manage.py createdb fails "cannot import name SingletonAdmin" for adept Theme

### ISSUE THREAD

**Issue by abuzabdi** [stephenmcd/mezzanine#1913]
Hi

I came across below issue while trying to use recently purchased Mezzanine Theme = Adept, kindly advise how to fix this issue

Thanks!
BR
Napoleon

(env) [nap@centosweb adept]$ python manage.py createdb
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nap/Web-Sites/new_multiLang-skybird/paid_themes/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/nap/Web-Sites/new_multiLang-skybird/paid_themes/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/nap/Web-Sites/new_multiLang-skybird/paid_themes/env/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/nap/Web-Sites/new_multiLang-skybird/paid_themes/env/lib/python2.7/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/home/nap/Web-Sites/new_multiLang-skybird/paid_themes/env/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/home/nap/Web-Sites/new_multiLang-skybird/paid_themes/env/lib/python2.7/site-packages/mezzanine/boot/__init__.py", line 114, in autodiscover
    django_autodiscover(*args, **kwargs)
  File "/home/nap/Web-Sites/new_multiLang-skybird/paid_themes/env/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/nap/Web-Sites/new_multiLang-skybird/paid_themes/env/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/nap/Web-Sites/new_multiLang-skybird/paid_themes/adept/theme/admin.py", line 4, in <module>
    from mezzanine.core.admin import TabularDynamicInlineAdmin, SingletonAdmin
 **### ImportError: cannot import name SingletonAdmin**

**Comment by stephenmcd** [comment]
Could you post this to the mailing list? Thanks

**Comment by abuzabdi** [comment]
Hi Stephen,  already done it.

https://groups.google.com/forum/#!topic/mezzanine-users/nPjZKCxGFNY

 hopefully can be fix it soon because I have to deliver a new site within few days

Appreciated
Nap

**Comment by abuzabdi** [comment]
Great , I see issue has been close . 
Could you plz share the solution ?
