### ISSUE TITLE
Adept theme: modeltranslation.translator.NotRegistered: The model "HomePage" is not registered for translation

### ISSUE THREAD

**Issue by abuzabdi** [stephenmcd/mezzanine#1915]
Hello

I got following error while trying to activate USE_MODELTRANSLATION = True 

**### modeltranslation.translator.DescendantRegistered: Model "Page" cannot be registered after its subclass "Form"**

I apply suggested solution 

https://github.com/stephenmcd/mezzanine/issues/1230

from settings.py I place .pages right after theme

INSTALLED_APPS = (
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.redirects",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    "django.contrib.staticfiles",
    "theme",
    "mezzanine.pages",
    "mezzanine.boot",
    "mezzanine.conf",
    "mezzanine.core",
    "mezzanine.generic",
    "mezzanine.blog",
    "mezzanine.forms",
    "mezzanine.galleries",
    "mezzanine.twitter",
    #"mezzanine.accounts",
    #"mezzanine.mobile",
    "theme.blog_mods",
    "theme.portfolio",
)

and Now I getting following error

env) [nap@centosweb adept]$ python manage.py sync_translation_fields
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nap/Web-Sites/skybird_multi_adept/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/nap/Web-Sites/skybird_multi_adept/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/nap/Web-Sites/skybird_multi_adept/env/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/nap/Web-Sites/skybird_multi_adept/env/lib/python2.7/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/home/nap/Web-Sites/skybird_multi_adept/env/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/home/nap/Web-Sites/skybird_multi_adept/env/lib/python2.7/site-packages/mezzanine/boot/__init__.py", line 114, in autodiscover
    django_autodiscover(*args, **kwargs)
  File "/home/nap/Web-Sites/skybird_multi_adept/env/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/nap/Web-Sites/skybird_multi_adept/env/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/nap/Web-Sites/skybird_multi_adept/adept/theme/admin.py", line 27, in <module>
    admin.site.register(HomePage, HomePageAdmin)
  File "/home/nap/Web-Sites/skybird_multi_adept/env/lib/python2.7/site-packages/mezzanine/boot/lazy_admin.py", line 30, in register
    super(LazyAdminSite, self).register(*args, **kwargs)
  File "/home/nap/Web-Sites/skybird_multi_adept/env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 125, in register
    self._registry[model] = admin_class(model, self)
  File "/home/nap/Web-Sites/skybird_multi_adept/env/lib/python2.7/site-packages/mezzanine/core/admin.py", line 270, in __init__
    super(ContentTypedAdmin, self).__init__(*args, **kwargs)
  File "/home/nap/Web-Sites/skybird_multi_adept/env/lib/python2.7/site-packages/mezzanine/core/admin.py", line 104, in __init__
    super(DisplayableAdmin, self).__init__(*args, **kwargs)
  File "/home/nap/Web-Sites/skybird_multi_adept/env/lib/python2.7/site-packages/modeltranslation/admin.py", line 247, in __init__
    super(TranslationAdmin, self).__init__(*args, **kwargs)
  File "/home/nap/Web-Sites/skybird_multi_adept/env/lib/python2.7/site-packages/modeltranslation/admin.py", line 25, in __init__
    self.trans_opts = translator.get_options_for_model(self.model)
  File "/home/nap/Web-Sites/skybird_multi_adept/env/lib/python2.7/site-packages/modeltranslation/translator.py", line 574, in get_options_for_model
    'translation' % model.__name__)
**### modeltranslation.translator.NotRegistered: The model "HomePage" is not registered for translation**
(env) [nap@centosweb adept]$

Kindly advise

BR
Napoleon

**Comment by abuzabdi** [comment]
Hi

Issue fixed   after creating translate.py as per customized models(HomePage) modelTranslation

Reference:
"Adding translation fields to your custom models" from this blog:
https://leehodgkinson.com/blog/multilingual-theme-in-mezzanine/

and 
https://mezzanine.readthedocs.io/en/latest/multi-lingual-sites.html#translation-fields-for-custom-applications

BR
