### ISSUE TITLE
Win10, pip install retrogrades Jango to 1.11.29, then when creating myproject, ModuleNotFoundError: No module named 'django.utils.importlib'

### ISSUE THREAD

**Issue by aarek-eng** [stephenmcd/mezzanine#1990]
```
Installing collected packages: django
  Attempting uninstall: django
    Found existing installation: Django 3.2.4
    Uninstalling Django-3.2.4:
      Successfully uninstalled Django-3.2.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
wagtail 2.13.2 requires Django<3.3,>=2.2, but you have django 1.11.29 which is incompatible.
nemo 3.11.0 requires Django==2.2.24, but you have django 1.11.29 which is incompatible.
djangorestframework 3.12.4 requires django>=2.2, but you have django 1.11.29 which is incompatible.
django-treebeard 4.5.1 requires Django>=2.2, but you have django 1.11.29 which is incompatible.
django-sekizai 2.0.0 requires django>=2.2, but you have django 1.11.29 which is incompatible.
django-formtools 2.3 requires Django>=2.2, but you have django 1.11.29 which is incompatible.
django-filter 2.4.0 requires Django>=2.2, but you have django 1.11.29 which is incompatible.
django-cms 3.8.0 requires Django>=2.2, but you have django 1.11.29 which is incompatible.
django-classy-tags 2.0.0 requires django>=2.2, but you have django 1.11.29 which is incompatible.
Successfully installed django-1.11.29
```

```
Traceback (most recent call last):
  File "c:\users\USERNAME\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\USERNAME\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\Scripts\mezzanine-project.exe\__main__.py", line 4, in <module>
  File "c:\users\USERNAME\appdata\local\programs\python\python39\lib\site-packages\mezzanine\bin\mezzanine_project.py", line 11, in <module>
    from mezzanine.utils.importing import path_for_import
  File "c:\users\USERNAME\appdata\local\programs\python\python39\lib\site-packages\mezzanine\utils\importing.py", line 5, in <module>
    from django.utils.importlib import import_module
 ModuleNotFoundError: No module named 'django.utils.importlib'`
```

**Comment by jerivas** [comment]
Are you installing Mezzanine from master or from pip? Compatibility with Django 2+ requires installing from master at the moment
